# Generated by Django 5.2.6 on 2025-09-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Awareness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("photo", models.ImageField(upload_to="awareness_photos/")),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="awareness_pdfs/"
                    ),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
                ("is_event", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
