# Generated by Django 5.2.6 on 2025-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
