# Generated by Django 4.2.25 on 2025-11-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('medium', 'Medium'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
