# Generated by Django 4.2.25 on 2026-02-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="health_document",
            field=models.FileField(
                blank=True,
                help_text="Optional: Upload your background health document (PDF, images, etc.)",
                null=True,
                upload_to="appointment_health_docs/",
            ),
        ),
    ]
