# Generated by Django 4.2.25 on 2025-11-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': []},
        ),
    ]
